In [22]:
#The null hypothesis       : the two distributions are identical, F(x) = G(x) for all x
#The alternative hypothesis: the two distributions are not identical, , F(x) != G(x) for all x

# If my pvalue is more than 0.05, then we will accept null hypothesis...
# If my pvalue is less than 0.05, then we will reject null hypothesis...

In [23]:
import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
response = stats.ks_2samp(sample1, sample2)

In [24]:
sample1

array([0.72062722, 0.42819335, 0.60144552, 0.77326439, 0.76957347,
       0.67383667, 0.73572385, 0.57592133, 0.98992382, 0.9935056 ,
       0.25583876, 0.60365726, 0.65094631, 0.33511799, 0.7880146 ,
       0.99943126, 0.12105363, 0.60939007, 0.30821855, 0.61234482,
       0.30866547, 0.97802649, 0.48482478, 0.47667267, 0.03590268,
       0.80688032, 0.48780202, 0.42352044, 0.70690566, 0.3067802 ,
       0.89801963, 0.48982445, 0.77282391, 0.45157587, 0.4201143 ,
       0.43729653, 0.4224499 , 0.1284856 , 0.90626643, 0.3191538 ,
       0.99725346, 0.4247315 , 0.22071133, 0.9235735 , 0.78963177,
       0.44844271, 0.43879901, 0.51955877, 0.35724959, 0.94972234,
       0.54769245, 0.80095698, 0.04363518, 0.12971165, 0.91293057,
       0.43786189, 0.2964978 , 0.9262609 , 0.51660424, 0.50427554,
       0.00734207, 0.77285178, 0.39065557, 0.38582905, 0.58171071,
       0.13621578, 0.42309095, 0.36774264, 0.67447198, 0.4326473 ,
       0.53764207, 0.59271578, 0.86422083, 0.23699484, 0.14326

In [25]:
sample2

array([-0.41700923,  1.42031192,  0.72973631, -1.5624782 ,  0.01054251,
       -1.28805298, -0.79877689,  1.41282386,  2.08541319, -0.93478488,
       -0.4225971 ,  0.65307229, -0.74911826,  0.67076395, -2.05775082,
        0.71100862,  0.65469192, -0.41298176, -0.22029714, -1.77798045,
        1.79521154, -1.45684907, -0.95110738,  0.12880318, -0.6433726 ,
        0.43134845, -2.50673359, -0.57653195, -1.27159963,  1.31423484,
       -0.47702944, -0.6452402 ,  0.40469036,  0.56850437, -2.35743783,
        0.96715806, -1.22741586,  1.11621597, -0.50886021, -0.36518234,
       -1.87786511, -0.7119653 , -0.79309569,  0.67190968, -1.8925649 ,
        0.61127256,  0.90726971, -0.366748  , -0.09202653,  1.42239805,
       -0.81608318, -0.79296998,  0.54331683, -1.38141691, -0.14542274,
        0.17063786, -0.80760103, -0.02242445,  1.20630902,  0.95465489,
        0.87755452, -0.41941438,  0.00907441,  0.03605339,  0.74712124,
       -1.36804357,  0.70522386,  0.61246983, -0.79943592, -1.04

In [27]:
# If my pvalue is less than 0.05, then we will reject null hypothesis, it means trained data and new incomming training data both have not same data distribution....
# So, we have to retrain our model with new incomming train data....
response.pvalue, round(response.pvalue, 3)

(6.42251331986378e-17, 0.0)

In [29]:

#Anomly in my dataset
# 
# 1.High Null Value
# 2. Missing COlumns
# 3. Outlier
# 4. Categorical: 
# Gender--> MALE, FEMALE,OTHER

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("/config/workspace/aps_failure_training_set1.csv")
df

class  aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000  ag_001  \
0       pos  153204      0         182     na      0      0      0       0   
1       pos  453236     na        2926     na      0      0      0       0   
2       pos   72504     na        1594   1052      0      0      0     244   
3       pos  762958     na          na     na     na     na    776  281128   
4       pos  695994     na          na     na     na     na      0       0   
...     ...     ...    ...         ...    ...    ...    ...    ...     ...   
36183   neg  153002     na         664    186      0      0      0       0   
36184   neg    2286     na  2130706538    224      0      0      0       0   
36185   neg     112      0  2130706432     18      0      0      0       0   
36186   neg   80292     na  2130706432    494      0      0      0       0   
36187   neg   40222     na         698    628      0      0      0       0   

        ag_002  ...   ee_002   ee_003   ee_004   ee_005   ee_006  ee_007  \
0            0  ...   129862    26872    34044    22472    34362       0   
1          222  ...  7908038  3026002  5025350  2025766  1160638  533834   
2       178226  ...  1432098   372252   527514   358274   332818  284178   
3      2186308  ...       na       na       na       na       na      na   
4            0  ...  1397742   495544   361646    28610     5130     212   
...        ...  ...      ...      ...      ...      ...      ...     ...   
36183        0  ...   998500   566884  1290398  1218244  1019768  717762   
36184        0  ...    10578     6760    21126    68424      136       0   
36185        0  ...      792      386      452      144      146    2622   
36186        0  ...   699352   222654   347378   225724   194440  165070   
36187        0  ...   440066   183200   344546   254068   225148  158304   

       ee_008  ee_009 ef_000 eg_000  
0           0       0      0      0  
1      493800    6914      0      0  
2        3742       0      0      0  
3          na      na     na     na  
4           0       0     na     na  
...       ...     ...    ...    ...  
36183  898642   28588      0      0  
36184       0       0      0      0  
36185       0       0      0      0  
36186  802280  388422      0      0  
36187  170384     158      0      0  

[36188 rows x 171 columns]

In [9]:
df = pd.read_csv("/config/workspace/artifact/12222022__184746/data_ingestion/dataset/train.csv")
df

class  aa_000  ab_000        ac_000  ad_000  ae_000  af_000  ag_000  \
0       neg      22     2.0  4.400000e+01     NaN     0.0     0.0     0.0   
1       neg      10     NaN  0.000000e+00     0.0     0.0     0.0     0.0   
2       neg   41474     NaN  5.980000e+02     NaN     0.0     0.0     0.0   
3       neg   18928     NaN  1.406000e+03  1406.0     0.0     0.0     0.0   
4       neg      26     NaN  2.000000e+01    20.0     0.0     0.0     0.0   
...     ...     ...     ...           ...     ...     ...     ...     ...   
28945   neg  180262     NaN  0.000000e+00     NaN     0.0     0.0     0.0   
28946   neg   39754     NaN  4.900000e+02   466.0     0.0     0.0     0.0   
28947   neg    1798     NaN  4.400000e+01    36.0     0.0     0.0     0.0   
28948   neg  179692     0.0  2.130706e+09   704.0    18.0    34.0     0.0   
28949   neg   30766     NaN  5.260000e+02   506.0     0.0     0.0     0.0   

       ag_001  ag_002  ...     ee_002    ee_003     ee_004     ee_005  \
0         0.0  3454.0  ...      196.0      34.0       46.0       24.0   
1         0.0     0.0  ...       36.0      26.0       36.0       46.0   
2         0.0     0.0  ...   331610.0  177770.0   348412.0   315844.0   
3         0.0     0.0  ...    58134.0    5134.0     1764.0       92.0   
4         0.0     0.0  ...      508.0      76.0       72.0        0.0   
...       ...     ...  ...        ...       ...        ...        ...   
28945     0.0     0.0  ...  1519772.0  988792.0  3290222.0  1440160.0   
28946     0.0     0.0  ...   181658.0   96452.0   270364.0   344880.0   
28947     0.0     0.0  ...     9082.0    6750.0    16788.0    12258.0   
28948     0.0     0.0  ...   486262.0  254052.0   394340.0   308248.0   
28949     0.0     0.0  ...   181734.0   88012.0   194604.0   396336.0   

         ee_006     ee_007    ee_008   ee_009  ef_000  eg_000  
0          10.0        0.0       0.0      0.0     0.0     0.0  
1         100.0       26.0       0.0      0.0     0.0     0.0  
2      237834.0   148534.0  258180.0  15748.0     0.0     0.0  
3          14.0        0.0       0.0      0.0     0.0     0.0  
4           0.0        0.0       0.0      0.0     0.0     0.0  
...         ...        ...       ...      ...     ...     ...  
28945  588876.0   259714.0  385322.0  31364.0     0.0     0.0  
28946  382150.0   238500.0  192166.0   1652.0     0.0     0.0  
28947   10300.0     8948.0   14866.0    140.0     0.0     0.0  
28948  926104.0  1086352.0   18538.0      0.0     0.0     0.0  
28949  181866.0   113420.0  166686.0  17838.0     0.0     0.0  

[28950 rows x 171 columns]

In [10]:
df.isnull().sum()

class         0
aa_000        0
ab_000    22358
ac_000     1723
ad_000     7413
          ...  
ee_007      305
ee_008      305
ee_009      305
ef_000     1398
eg_000     1397
Length: 171, dtype: int64

In [11]:
df.isnull().sum()/df.shape[0]

class     0.000000
aa_000    0.000000
ab_000    0.772297
ac_000    0.059516
ad_000    0.256062
            ...   
ee_007    0.010535
ee_008    0.010535
ee_009    0.010535
ef_000    0.048290
eg_000    0.048256
Length: 171, dtype: float64

In [12]:
(df.isnull().sum()/df.shape[0]).values

array([0.        , 0.        , 0.77229706, 0.05951641, 0.25606218,
       0.04431779, 0.04431779, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01098446, 0.01074266, 0.01074266,
       0.0784456 , 0.01088083, 0.01074266, 0.01088083, 0.00974093,
       0.01088083, 0.00974093, 0.04825561, 0.01074266, 0.01074266,
       0.01074266, 0.04435233, 0.04435233, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01098446, 0.04829016,
       0.04829016, 0.04438687, 0.04431779, 0.01088083, 0.01088083,
       0.00974093, 0.00974093, 0.37920553, 0.44770294, 0.65274

In [13]:
(df.isnull().sum()/df.shape[0]).index

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [15]:
for column_name, missing_percentage in zip((df.isnull().sum()/df.shape[0]).index,(df.isnull().sum()/df.shape[0]).values):
    print(column_name, missing_percentage)

class 0.0
aa_000 0.0
ab_000 0.7722970639032816
ac_000 0.05951640759930915
ad_000 0.2560621761658031
ae_000 0.044317789291882556
af_000 0.044317789291882556
ag_000 0.010535405872193437
ag_001 0.010535405872193437
ag_002 0.010535405872193437
ag_003 0.010535405872193437
ag_004 0.010535405872193437
ag_005 0.010535405872193437
ag_006 0.010535405872193437
ag_007 0.010535405872193437
ag_008 0.010535405872193437
ag_009 0.010535405872193437
ah_000 0.010984455958549223
ai_000 0.0107426597582038
aj_000 0.0107426597582038
ak_000 0.07844559585492228
al_000 0.010880829015544042
am_0 0.0107426597582038
an_000 0.010880829015544042
ao_000 0.009740932642487047
ap_000 0.010880829015544042
aq_000 0.009740932642487047
ar_000 0.04825561312607945
as_000 0.0107426597582038
at_000 0.0107426597582038
au_000 0.0107426597582038
av_000 0.04435233160621762
ax_000 0.04435233160621762
ay_000 0.010535405872193437
ay_001 0.010535405872193437
ay_002 0.010535405872193437
ay_003 0.010535405872193437
ay_004 0.0105354058721

In [16]:
drop_column_names=[]
for column_name, missing_percentage in zip((df.isnull().sum()/df.shape[0]).index,(df.isnull().sum()/df.shape[0]).values):
    if missing_percentage>.3:
        drop_column_names.append(column_name)

In [17]:
drop_column_names

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [18]:
null_report = df.isnull().sum()/df.shape[0]

In [19]:
null_report[null_report>.3]

ab_000    0.772297
bk_000    0.379206
bl_000    0.447703
bm_000    0.652746
bn_000    0.725250
bo_000    0.762383
bp_000    0.785009
bq_000    0.802073
br_000    0.810743
cr_000    0.772297
dtype: float64

In [20]:
null_report[null_report>.3].index

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')